PGPI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from PGPI import settings

from app import views as vapp
from estaticas import views as eapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',vapp.inicio,),
    path('registro/',vapp.registro, name='registro'),
    path('app/', include('app.urls')),
    path('eapp/',include('estaticas.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from PGPI import settings
from django.conf.urls.static import static 
from . import views as v

urlpatterns = [ 
    path('detalle/<int:id_botas>/',v.añadir_bota_al_carrito.as_view(), name="detalleProd"),
    path('base/', v.base),
    path('catalogo/', v.catalogo),
    path('añadirBotaAlCarrito/', v.añadir_bota_al_carrito.as_view()),
    path('carritoDeCompra/', v.carrito_de_compra, name='carritoDeCompra'),
    path('compra/',v.Comprar.as_view(), name='compra'),
    path('atencionCliente/',v.AtencionC.as_view(), name='atencionCliente'),
    path('seguimiento/',v.Seguimiento.as_view(), name='seguimiento'),
    path(' ',v.inicio, name ='inicio'),
    path('buscar/',v.buscar_bota,name="buscar_bota"),
    path('borrarBotaCarrito/<int:id_botaC>/',v.borrarElemCarrito,name="borrarElemCarrito"),
    path('filtroMarca/',v.filtro_marca,name="filtro_marca")

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
import random
import string
from django.db import models
from django import forms

# Create your models here.

class Botas(models.Model):
    nombre = models.CharField(max_length=50)
        

    TIPOS_SUELA=(("Cesped Natural","Cesped Natural"),
    ("Cesped Artificial","Cesped Artificial"),
    ("Indoor","Indoor"))    
    suela = models.CharField(max_length=30, choices=TIPOS_SUELA, default="Cesped Natural")
    descripcion = models.TextField(max_length=200)
    GAMAS =(("A","Alta"),
    ("M","Media"),
    ("B","Baja"))
    gama =models.CharField(max_length=2,choices=GAMAS,default="M")
    marca = models.CharField(max_length=50)
    precio = models.DecimalField(max_digits=5,decimal_places=2)

    TALLAS=(("T38","38"),
    ("T39","39"),
    ("T40","40"),
    ("T41","41"),
    ("T42","42"),
    ("T43","43"),
    ("T44","44"),
    ("T45","45"),
    ("T46","46"))
    talla = models.CharField(max_length=3,choices=TALLAS,default="T42")
    imagen = models.ImageField(upload_to='', null=True, blank=True)
    agotado = models.BooleanField(default=False)

class Carrito(models.Model):
    creation_date = models.DateTimeField()

class BotasCarrito(models.Model):
    bota = models.ForeignKey(Botas, on_delete=models.CASCADE)
    #carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, null = True)
    cantidad = models.IntegerField()


def random_id(lenght=5):
    return ''.join(random.choice(string.digits) for x in range(lenght))    

class Pedido(models.Model):
    nombre=models.CharField(max_length=20, blank=False, null=False,help_text="Nombre")
    apellidos=models.CharField(max_length=20,blank=False, null=False)
    telefono = models.CharField(max_length=11,blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    direccion = models.CharField(max_length=150,blank=False, null=False)
    PAGO = (('Contrareembolso','Contrareembolso'),('PaaS','Paas'))
    formaPago = models.CharField(max_length=20,choices=PAGO,default="Contrareembolso",blank=False, null=False)
    idSeguimiento = models.CharField(max_length=5, default=random_id, editable=True)
    ESTADOS = (('En almacén','En almacén'), ('En reparto', 'En reparto'), ('Entregado', 'Entregado'))
    estado =  models.CharField(max_length=20,choices=ESTADOS,default="En almacén",blank=False, null=False)
    


class AtencionC(models.Model):
    email = models.EmailField(blank=False, null=False)
    asunto = models.CharField(max_length=150, null = False)
    descripcion = models.TextField(null=False)



    
    

app/templates/atencionCliente.html
{% extends 'base.html' %}


{% block encabezado %} {% endblock %}
{% block contenido %}

<form
action=""   method="POST" name="atencionC">
{% csrf_token %}
<div class="container-fluid" style="font-size: 1.5rem;">
    <div class="row text-center mt-5">
        <p class = "col-md text-center"> Contacta con nosotros</p>
    </div>
    <div class="row text-center mt-5">
        <div class="col-md text-center"><input type="email" required="true" name="email" placeholder="Correo electrónico"></div></div>
        <div class="row text-center mt-5">
        <div class="col-md text-center"><input type="text" required="true" name="asunto" placeholder="Asunto"></div></div>
        <div class="row text-center mt-5">
        <div class="col-md text-center"><textarea type="text" required="true" name="descripcion" placeholder="Descripción"></textarea></div></div>
    
    <br></br>
 

    <div class="row d-grid gap-2 col-6 mx-auto"><button style="font-size: 2rem;" class="btn btn-dark btn-sm" type="submit">Enviar</button></div>
    <br></br>
</div>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>

<html lang='es'>
<head>
  <meta charset='utf-8'>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  
  <link rel="stylesheet" src="styles.css">
  

</head> 
<body>
  <style>
    footer {

      position:fixed;
   left:0px;
   bottom:0px;
   height:30px;
   width:100%;
   background:#999;
}
  </style>
  <header> 
  	{% block encabezado %}{% endblock %}
  	<nav class="navbar navbar-expand-lg" style="background-color: #9C718C;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'inicio' %}">FootBoot</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/app/catalogo/">Catálogo de productos </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/app/seguimiento/">Seguimiento de pedidos </a>
            </li>
           
          </ul>
        </div>
        
        
        
        <form action="{% url 'buscar_bota' %}" method="POST">
          
          {% csrf_token %}
          
          <input type="search" name="searched" placeholder="Busqueda de producto">
          <button style="color: black;" class="btn btn-outline-secondary btn-primary" type="submit">Buscar</button>
        </form>
        
        
        <div class="container-fluid">
        {% if user.is_authenticated %}
          <p style="float:right;">{{user.email}}</p>
        {% else %}
          <a style="font-style: none; color: floralwhite;" href="{% url 'registro' %}"><button type="button" class="btn btn-dark"> Registrate</button></a>
        {% endif %}</div>
        <a href="{% url 'carritoDeCompra' %}">
          <img src="/media/botas/pngwing.com.png" alt = "Carrito de compra" width="8%" style="float: right;">
        </a>
      </div>
    </nav>
  </header>
<body>
  {% block contenido %}{% endblock %}
  

</body>
  {% block pie %}
  <footer >
    <div class="row text-center" style="background-color: #9C718C;">
      <div class="col-md"><a  style="text-decoration:none ; color: rgb(29, 28, 28);" href="/eapp/privacidad">Aviso de privacidad</a></div>
      <div class="col-md"><a style="text-decoration:none ; color: rgb(29, 28, 28);"href="/eapp/terminos" >Términos de Uso</a></div>
      <div class="col-md"><a style="text-decoration:none ; color: rgb(29, 28, 28);"href="/eapp/empresa">Datos de la empresa</a></div>
      <div class="col-md"><a style="text-decoration:none ; color: rgb(29, 28, 28);"href="/app/atencionCliente">Atención al cliente</a></div>
      <div class="col-md"><a style="text-decoration:none ; color: rgb(29, 28, 28);"href="/eapp/devoluciones">Política de devolución</a></div>
      <div class="col-md"><a style="text-decoration:none ; color: rgb(29, 28, 28);"href="/eapp/envios">Política de envios</a></div>
    </div>
    {% endblock %}
  </footer>
</html>

app/templates/buscar.html
{% extends 'base.html' %}

{% block contenido %} 

{% if searched %}
    <h1>Has buscado: {{searched}}</h1>
{% endif %}

{% for bota in botas %}


{% if bota.agotado == True %}
<div class="row mt-5 text-center">
  <a  style="text-decoration: none; color: darkslategrey;"
    ><img
      src="{{bota.imagen.url}}"
      width="400px"
      height="400px"
      alt="Imagen Bota"
    />
    <div><strong class="text-center"  style="color: red;">PRODUCTO AGOTADO</strong></div>
    <div class="text-center">{{bota.nombre}}</div>

  </a>
</div>


{% else %}


<div class="row mt-5 text-center">
  <a href="{% url 'detalleProd' bota.id  %}" style="text-decoration: none; color: darkslategrey;"
    ><img
      src="{{bota.imagen.url}}"
      width="400px"
      height="400px"
      alt="Imagen Bota"
    />
    <div class="text-center">{{bota.nombre}}</div>
  </a>
</div>

{% endif %}
{% endfor %}

{% endblock %}

app/templates/carritoDeCompra.html
{% extends 'base.html' %} {% csrf_token %} {% block encabezado %} {% endblock %}
{% block contenido %} 
{% for botaC in botasC %}


<div class="row mt-5" style="border-color: grey; border-style: solid">
  <div class="col-md-4">
    <a href="{% url 'detalleProd' botaC.bota.id  %}" style="text-decoration:none ; color: black;">
    <img alt="bota" src="{{botaC.bota.imagen.url}}" height="80%" width="30%" />
  </a>
  </div>
  <div class="col-md-5">
    <div
      class="col-md"
      style="font-size: 1.5rem; font-family: Arial, Helvetica, sans-serif"
    >
      <strong>{{botaC.bota.nombre}}</strong>
    </div>
    <div class="col-md mt-5">Cantidad: {{botaC.cantidad}}</div>
  </div>
  <div class="col-md" style="font-size: 2rem">{{ botaC.bota.precio }} €</div>
  <div class="col-md-2">
    <a href="{% url 'borrarElemCarrito' botaC.id %}"  style="text-decoration: none;"><button type="button" class="btn btn-danger">Eliminar</button></a>
  </div>
</div>
{% endfor %}

<div class="row text-center mt-5"><div class="col-md" style="font-size: 1.75rem;"><strong>Total: {{ precioT }}</strong></div></div>
<div class="row text-center mt-5">
  <a href="{% url 'compra' %}" style="text-decoration: none;"><button type="button" class="btn btn-dark d-grid gap-2 col-6 mx-auto" style="font-size: 1.75rem;"><strong>PAGAR</strong></button></a></div>

{% endblock %}

app/templates/catalogo.html
{% extends 'base.html' %} {% csrf_token %} {% block encabezado %} {% endblock %}
{% block contenido %} 

<form action="{% url 'filtro_marca' %}" method="POST">
          
  {% csrf_token %}
  
  Filtrar por marca:
  <select name="filtro" placeholder="Filtrar por marca">
    {% for m in marcas%}
    <option>{{ m }}</option>
    {% endfor %}
  </select>
    
  Filtrar por gama:
  <select  name="filtroGama" placeholder="Filtrar por marca">
    {% for g in gamas%}
    <option >{{ g }}</option>
    {% endfor %}
  </select>
    <button style="color: black;" class="btn btn-outline-secondary btn-primary" type="submit">Filtrar</button>
  </form>




{% for bota in botas %}

{% if bota.agotado == True %}
<div class="row mt-5 text-center">
  <a  style="text-decoration: none; color: darkslategrey;"
    ><img
      src="{{bota.imagen.url}}"
      width="400px"
      height="400px"
      alt="Imagen Bota"
    />
    <div><strong class="text-center"  style="color: red;">PRODUCTO AGOTADO</strong></div>
    <div class="text-center">{{bota.nombre}}</div>

  </a>
</div>


{% else %}


<div class="row mt-5 text-center">
  <a href="{% url 'detalleProd' bota.id  %}" style="text-decoration: none; color: darkslategrey;"
    ><img
      src="{{bota.imagen.url}}"
      width="400px"
      height="400px"
      alt="Imagen Bota"
    />
    <div class="text-center">{{bota.nombre}}</div>
  </a>
</div>

{% endif %}
{% endfor %} {% endblock %}

app/templates/compra.html
{% extends 'base.html' %}


{% block encabezado %} {% endblock %}
{% block contenido %}

<form
action=""   method="POST" name="compra">
{% csrf_token %}
<div class="container-fluid" style="font-size: 1.5rem;">
    <div class="row text-center mt-5">
        <div class="col-md text-center"><input type="text"required="true" name="nombre" placeholder="Nombre"></div>
        <div class="col-md text-center"><input type="text"required="true" name="apellidos" placeholder="Apellidos"></div>
        <div class="col-md text-center"><input type="tel" required="true" name="telefono" placeholder="Teléfono"></div>
    </div>
    <div class="row mt-5 text-center">
        <div class="col-md-4">
            <input type="email" name="email" required="true" placeholder="Correo eletrónico">

        </div>
        <div class="row mt-5">
            <div class="col-md-4">
                <input type="text" name="direccion" required="true" placeholder="Dirección">
                
            </div>
            <div class="col-md"><strong>TOTAL: {{precioT}}</strong></div>
        </div>
    </div>
    <div class="row mt-5"><strong>Métodos de pago</strong></div>

    <div class="row ">
        <input type="radio" id="contrareembolso" required="true" name="pago" value="contrareembolso"  />
        <label for="pago">Contrareembolso</label>
        
    </div>

    <div class="row d-grid gap-2 col-6 mx-auto"><button style="font-size: 2rem;" class="btn btn-dark btn-sm" type="submit">FINALIZAR</button></div>

</div>
</form>
{% endblock %}

app/templates/compra_realizada.html
<p>
    Hola! {{ nombre }} {{ apellidos }}
</p>
<p>
    Hemos recibido tu pedido.
</p>
<p>
    <strong>Direccion:</strong> {{ direccion }}
</p>
<p>
    <strong>Telefono:</strong> {{ telefono }}
</p>
<p>
    <strong>Método de pago:</strong> {{ metodoPago }}
</p>
<p>
    <strong>Email:</strong> {{ email }}
</p>
<p>
    <strong>Importe total:</strong>  {{precioT}}
</p>

El identificador para ver el estado de su pedido es: {{idSeguimiento}}

app/templates/correo_atencionCliente.html
<p>
    Hola! 
</p>
<p>
    Hemos recibido tu incidencia.
</p>
<p>
    <strong>Título:</strong> {{ asunto }}
</p>
<p>
    <strong>Descripción:</strong> {{ descripcipn }}
</p>

<p>
    <strong>Email:</strong> {{ email }}
</p>
<p>
    <strong>Muchas gracias.</strong> 
</p>

app/templates/detalleProd.html
{% extends 'base.html' %} {% block encabezado %}

{% csrf_token %}


{% endblock %} {% block contenido %}



<form action=""   method="post" name="compra">
  <div class="container-fluid">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-8 mt-5" >
      <img src="{{botas.imagen.url}}" alt="altura" width="50%" />
    </div>
    
    <div class="col-md-4 mt-5" style="font-size: 20px;" >
      <div class="row mt-5">
        <strong
          ><input
            style="font-size: 3rem; border: 0; border-style: none"
            type="text"
            value="{{botas.nombre}}"
            readonly="True"
        /></strong>
      </div>  
      <div class="row mt-5" >
        <label class="required" for="id_descripcion"
          >Descripción:
          <textarea  readonly="True">{{botas.descripcion}}</textarea></label>
      </div>
      <div class="row  mt-5">
        <div class="col-md">Suela: {{botas.suela}}</div>
        <div class="col-md">
          Gama: {{botas.gama}}
        </div>
      </div>
      <div class="row  mt-5">
        <div class="col-md">Marca: {{botas.marca}}</div>
        <div class="col-md">
          <label class="required" for="id_talla">Talla:</label>
          <select name="talla" id="id_talla">
            <option value="T38">38</option>

            <option value="T39">39</option>

            <option value="T40">40</option>

            <option value="T41">41</option>

            <option value="T42" selected="">42</option>

            <option value="T43">43</option>

            <option value="T44">44</option>

            <option value="T45">45</option>

            <option value="T46">46</option>
          </select>
        </div>
      </div>

      <div class="row mt-5 ">
        <div class="col-md" >Precio: {{botas.precio}} €</div>
        <div class="col-md"><label class="required" for="id_cantidad">Cantidad:</label>
          <select name="cantidad" id="id_cantidad">
            <option value="1" selected="">1</option>

            <option value="2">2</option>

            <option value="3">3</option>

            <option value="4">4</option>

            <option value="5" >5</option>

            <option value="6">6</option>

            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>

         
          </select>
          
        </div>
        <div class="col-md">
          <button class="btn btn-info" type="submit">Añadir a la cesta</button>
        </div>
      </div>
    </div>
  </div>
</div>
</form>
{% endblock %}

app/templates/detallesSeguimiento.html
{% extends 'base.html' %}


{% block encabezado %} {% endblock %}
{% block contenido %}



{% csrf_token %}
<div class="container-fluid" style="font-size: 1.5rem;">
    <div class="row text-center mt-5">
       
        <p class = "col-md text-center"> El estado actual del pedido con ID <strong>{{pedido.idSeguimiento}}</strong> es:      <strong>{{pedido.estado}}</strong></p>
        
    </div>
   

    
</div>

{% endblock %}

app/templates/form_registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <title>Registro de usuario</title>
</head>

<body>
    <div class="container">
        <br>
        <br>
        <br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-body">
                        <h2>Registro de usuario</h2>
                        <hr>
                        <form action="" method="post">
                            {% load crispy_forms_tags %}
                            {{ form | crispy }}
                            {% csrf_token %}
                            <br>
                            <br>
                            <input type="submit" value="registrar" class="btn btn-success float-end">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

app/templates/inicio.html
{% extends 'base.html' %}

  {% block contenido %}
      {% load static %}
        <img src="/media/botas/futbolfondoas.jpg" class="img-fluid" alt="Logo" width="100%" >
  {% endblock %}

app/templates/seguimientoForm.html
{% extends 'base.html' %}


{% block encabezado %} {% endblock %}
{% block contenido %}

<form
action=""   method="POST" name="seguimiento">
{% csrf_token %}
<div class="container-fluid" style="font-size: 1.5rem;">
    <div class="row text-center mt-5">
        <p class = "col-md text-center"> Realiza un seguimiento de su pedido</p>
        <br></br>
        <p class = "col-md text-center"> Introduzca el ID de su pedido.</p>
    </div>
    <div class="row text-center mt-5">
        <div class="col-md text-center"><input type="text" required="true" name="idSeguimiento" placeholder="ID del pedido"></div></div>
      
    
    <br></br>
 

    <div class="row d-grid gap-2 col-6 mx-auto"><button style="font-size: 2rem;" class="btn btn-dark btn-sm" type="submit">Realizar seguimiento</button></div>
    <br></br>
</div>
</form>
{% endblock %}